### ISSUE TITLE
cMakeLists compliation error

### ISSUE THREAD

**Issue by xh2g20soton** [federicorossifr/cppposit#14]
I tried to compile with command cmake . but get an error message
[Terminal Saved Output.txt](https://github.com/federicorossifr/cppposit/files/12873656/Terminal.Saved.Output.txt)

**Comment by federicorossifr** [comment]
Hi,
Some examples in the `examples` folder require the Eigen library. Anyway, you should be able to compile the other examples, just ignoring the CMake error. 

If you want to compile all the examples (including the Eigen ones) you can follow the guide to install the prerequisites here: https://federicorossifr.github.io/cppposit/
